title: Differential Equation for Ecologists
description: A tutorial on differential equations in population biology.
markdown: kramdown
theme: minima  # You can choose a different theme if you prefer

kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true

# Specify the default layout
defaults:
  -
    scope:
      path: "" # All files in the project
      type: "pages"
    values:
      layout: "default"
