plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  -head.html
kramdown:
  math_engine: mathjax
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true
